import streamlit as st
# https://docs.streamlit.io/develop/quick-reference/cheat-sheet

st.set_page_config(layout="wide")

st.subheader("Roberto's- Cybersecurity (Python and Artificial Intelligence)")
st.write()
st.balloons()
st.snow()
st.toast("Loading...")

col1, col2 = st.columns([6, 1], gap="small", vertical_alignment="top", border=True, width="stretch")

with col1:
    st.success("CYBERSECURITY TOOL -> Constants for configuring the Google custom search API")
    st.warning("CYBERSECURITY TOOL -> Perform searches using the Google custom search API.")
    st.info("CYBERSECURITY TOOL -> Perform searches using the Google custom search API: Command Line")
    st.error("CYBERSECURITY TOOL -> Perform a Google search using an API KEY and a SEARCH ENGINE ID stored in a .env file.")
    st.success("CYBERSECURITY TOOL -> Perform a Google search and downloads files from URLs and save them locally.")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
    st.warning("CYBERSECURITY TOOL -> ...")
    st.info("CYBERSECURITY TOOL -> ...")
    st.error("CYBERSECURITY TOOL -> ...")
    st.success("CYBERSECURITY TOOL -> ...")
with col2:
    st.link_button("Code Github", "https://github.com/web-roberto/cybersecurity_python/blob/main/1_1_1_hacking_buscadores_parte1/ninjadorks.py")
    st.write('')
    st.link_button("Code Github", "https://github.com/web-roberto/cybersecurity_python/tree/main/1_1_3_ejecucion_scripts_python")
    st.write('')
    st.link_button("Code Github", "https://github.com/web-roberto/cybersecurity_python/tree/main/1_1_4_argumentos_linea_comandos")
    st.write('')
    st.link_button("Code Github", "https://github.com/web-roberto/cybersecurity_python/tree/main/1_1_5_generacion_resultados")
    st.write('')
    st.link_button("Code Github", "https://github.com/web-roberto/cybersecurity_python/tree/main/1_1_6_manejo_ficheros")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
    st.link_button("Code Github", "")
    st.write('')
